### ISSUE TITLE
Where can we got the pytorch version?

### ISSUE THREAD

**Issue by Reeshark** [microsoft/gated-graph-neural-network-samples#10]
Hi, author. Where can we got the pytorch version?

**Comment by mallamanis** [comment]
Hi, This fork https://github.com/thaonguyen19/gated-graph-neural-network-samples has a PyTorch implementation.

**Comment by Reeshark** [comment]
thx

**Comment by mallamanis** [comment]
Another newer, sparse version can also be found here: https://github.com/pcyin/pytorch-gated-graph-neural-network/
