### ISSUE TITLE
UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape.

### ISSUE THREAD

**Issue by fengjunhui** [Microsoft/gated-graph-neural-network-samples#11]
There is a UserWarning problem when I run 
`python ./chem_tensorflow_sparse.py`.
This is the detail : 
`UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may  consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "`

**Comment by mmjb** [comment]
This is spurious warning, caused by the application of a `tf.nn.embedding_lookup` operation on a non-`Variable` object (namely, `node_states_per_layer[-1]`). While this /can/ lead to massive performance degradation, it does not do so in this case, and so the warning can be safely ignored.
