### ISSUE TITLE
Do you use GPU for training?

### ISSUE THREAD

**Issue by xuzhang5788** [microsoft/gated-graph-neural-network-samples#13]
Thank you for your great work.

When you train your model, do you set your tensorflow with GPU or not? How long will it take for your training? 

I pip install -r requirements.txt, then run. It showed that I am using CPU. Even though I install tensowflow-gpu, it still running on CPU. Any advice? Thanks a lot.

**Comment by xuzhang5788** [comment]
I solved this problem. Thanks.

**Comment by mmjb** [comment]
[Closing as indicated]
