### ISSUE TITLE
How to use the trained models? 

### ISSUE THREAD

**Issue by xuzhang5788** [microsoft/gated-graph-neural-network-samples#14]
After training, how to use those trained models? How to predict the properties of chemicals? Any examples? Thanks a lot.

**Comment by mmjb** [comment]
We don't have an explicit test mode at the moment in this example code release. You could one by using the existing code to load stored models (from the `--restore` option) and by modifying `make_model` in `chem_tensorflow.py` to expose the [computed values](https://github.com/Microsoft/gated-graph-neural-network-samples/blob/4c12514b4e7bfc45055021dfaca71fc5fe1d22ab/chem_tensorflow.py#L151) as a graph op accessible from the outside (i.e., by writing it to `self.ops`).

**Comment by 51alg** [comment]
For `chem_tensorflow_dense.py` we have a [short example](https://github.com/Microsoft/gated-graph-neural-network-samples/blob/4c12514b4e7bfc45055021dfaca71fc5fe1d22ab/chem_tensorflow_dense.py#L250) of what code for a test mode would look like after loading a stored model with `--restore`.

**Comment by xuzhang5788** [comment]
@51alg 
Thank you for your response. However, it is not very clear for me. Using --restore is for continuing training. Did you modify your "short example" which has a link in your reply? Is it the same file as chem_tensorflow_dense.py ? Thanks a lot

**Comment by 51alg** [comment]
I've added a command line argument `--evaluate` to `chem_tensorflow_dense.py` to make this easier. 

Example usage:

`$ python chem_tensorflow_dense.py`  (produces ./[hash]_model_best.pickle)
`$ python chem_tensorflow_dense.py --restore ./[hash]_model_best.pickle --evaluate`

**Comment by xuzhang5788** [comment]
Thank you @51alg
