### ISSUE TITLE
Unable to wget the sample data

### ISSUE THREAD

**Issue by xxsang** [microsoft/gated-graph-neural-network-samples#17]
Thank you for sharing the ggnn codes. When I was trying to run the testing samples, I found I cannot get the sample data from the target URL neither by using get_data.py nor wget (with "unable to establish SSL connection") nor curl ("SSL_ERROR_SYSCALL"). May I please know if you shared testing data sample is still reachable? Thanks a lot!

**Comment by mallamanis** [comment]
Hi, I can download the file without a problem with both `wget` or though the browser. Can you try downloading this with the browser or from another machine? Note that we do _not_ host that file, so we don't have any any visibility into this.

**Comment by xxsang** [comment]
> Hi, I can download the file without a problem with both `wget` or though the browser. Can you try downloading this with the browser or from another machine? Note that we do _not_ host that file, so we don't have any any visibility into this.

Thank a lot for checking. I have tried another network environment and it works. Sorry for the inconvenience caused and I will close this issue.
