### ISSUE TITLE
Dense for small graph?

### ISSUE THREAD

**Issue by thisiscam** [microsoft/gated-graph-neural-network-samples#18]
Hi,

I was wondering typically what on what order of the size of graph shall be classified as "small", so that the dense version will be more beneficial than sparse version? I know I can benchmark this myself, but some expert comments will give me a good prior! Thanks!

**Comment by mmjb** [comment]
Molecule-sized graphs (i.e., 20-50 nodes) seem to be slightly (but only very slightly) faster in the dense version. I plan on doing some light updates to the code base soon and will do some benchmarking to make that statement more precise.
