### ISSUE TITLE
Please explain comments like ' # [b x v x h]'

### ISSUE THREAD

**Issue by jenniferSun27** [microsoft/gated-graph-neural-network-samples#2]
Hello,
I'm reading your code and I'd like to use gnn in my work. I noticed that you added some comments like ' # [b x v x h]' in your code. I guess understanding these comments will help me understand these quickly. While I'm not sure about what these characters actually mean. Especially I can't figure out what 'b' means. Could you please explain what 'b','v','e','h' mean in chem_tensorflow_dense.py? It will help me a lot.

Thank you very much!
Jennifer

**Comment by mallamanis** [comment]
Hi Jennifer,
The comments are meant to represent the dimensionality of the tensors.

Thus, the `b x v x h` this means that the tensor has three dimensions: Batch size (`b`) is the number of graphs per batch, `v` is the max number of nodes/vertices per graph (in the dense implementation) and `h` is the size of the hidden dimension. The `e` stands for the number of edge types in the graph.

**Comment by jenniferSun27** [comment]
Thank you for your answering.
And I have another question, in the paper [https://arxiv.org/abs/1511.05493](url) it mentioned "node annotations" distinguished from "node labels", to mark special nodes by giving them different initial node annotations. While I couldn't find corresponding parts in this code. I guess it is due to this is not necessary for your chemical molecules problem. I‘d just like to make sure if you really ignored this, or just I didn't find it.

Thanks again.
Jennifer

**Comment by mmjb** [comment]
You are correct, we do not use this in our example application here. Our
initial node labels are computed during data loading, but you could add
additional information at that point, corresponding to the node annotations
from our paper.

Marc

**Comment by jenniferSun27** [comment]
Thanks a lot.
