### ISSUE TITLE
where are the gates during propagation

### ISSUE THREAD

**Issue by chengmengli06** [microsoft/gated-graph-neural-network-samples#20]
gates seems not used during propagation process

**Comment by mmjb** [comment]
The propagation (apart from the GCN implementation) uses gated recurrent units to combine the incoming information and the old node state, see e.g. here:
https://github.com/Microsoft/gated-graph-neural-network-samples/blob/ae106c3e3e44e1f208ea606516ecc23e1a3ed041/chem_tensorflow_sparse.py#L213

**Comment by chengmengli06** [comment]
why chem_tensorflow_dense.py has no gates, the dense one and the sparse one should be the same, but they does not looks to be the same? @mmjb

**Comment by mmjb** [comment]
It does, see here:
https://github.com/Microsoft/gated-graph-neural-network-samples/blob/ae106c3e3e44e1f208ea606516ecc23e1a3ed041/chem_tensorflow_dense.py#L115

**Comment by chengmengli06** [comment]
thks, if not using gates, is it able to train 4 layer gnn to similar precision? the paper does not compare the cases using gates and not using gates.

**Comment by mmjb** [comment]
We haven't explored this in detail, so I can't give definite answers, but in brief experiments, plain RNN cells performed less well. (This difference may go away with hyperparameter tuning, though)
