### ISSUE TITLE
It seems strange to set the lowest value of valid accuracy as the best result.

### ISSUE THREAD

**Issue by jenniferSun27** [microsoft/gated-graph-neural-network-samples#5]
In chem_tensorflow.py Line 279:"` if val_acc < best_val_acc `". It seems to choose smaller accuracy as the best result, so that the network always run 25 epochs.
Is this a mistaken?

Thank you very much.
Jennifer

**Comment by mmjb** [comment]
The "accuracy" here refers to "mean absolute error relative to chemical accuracy" (see Gilmer et al: "Neural Message Passing for Quantum Chemistry", Sect. 8 for details). For this, smaller is better, but I agree that the name of the measure is confusing...

**Comment by jenniferSun27** [comment]
Oh I see... Thank you for answering.
